services:
  forgejo-runner:
    image: ghcr.io/podmania/forgejo-runner:latest
    userns_mode: "keep-id"
    container_name: forgejo-runner
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
